- id: "config"
  name: "Iyan Z Armanda"
  role: "Full-Stack Software Engineer"
  email: "your.email@example.com"
  github: "https://github.com/iyanarmanda"
  linkedin: "https://www.linkedin.com/in/iyan-zuli-armanda-8a1383296"
  status: "open to work"
  domain: "portfolio.izuli.my.id"
  ogSkills: ["Developer", "Programmer", "DFIR"]
