- id: "config"
  name: "Ian Armanda"
  role: "Software Developer & Cybersecurity Investigator"
  email: "your.email@example.com"
  github: "https://github.com/iyanarmanda"
  linkedin: "https://linkedin.com/in/username"
  status: "open to work"
  domain: "portfolio.izuli.my.id"
  ogSkills: ["Fullstack", "JavaScript", "Rust"]
